name: "⁉️- Feature request"
description: Suggest an idea for this project
title: "🚀 -"
labels:
  - enhancement
assignees:
  - Donnerstagnacht
projects:
  - polity-live/3
type: Feature Request 
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: Describe the problem your feature request addresses.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your ideal solution.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: List any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps for implementation
      description: Step-by-step plan for implementing this feature.
      placeholder: |
        1. ...
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Additional context or screenshots.
    validations:
      required: false
