import type { InstantRules } from '@instantdb/react';

const rules = {
  amendments: {
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isAuthor',
      'auth.id == data.ref("user.id")',
      'isCollaborator',
      'auth.id in data.ref("collaborators.user.id")',
      'isGroupMember',
      'data.ref("group.id") in auth.ref("$user.memberships.group.id")',
      'isPublic',
      'data.visibility == "public"',
      'isAuthenticatedVisibility',
      'data.visibility == "authenticated"',
      'isPrivate',
      'data.visibility == "private"',
      'isPublicOrAuthenticatedOrAuthorized',
      'data.visibility == "public" || (data.visibility == "authenticated" && isAuthenticated) || (data.visibility == "private" && (isAuthor || isCollaborator)) || data.visibility == null || data.status == "published"',
      'hasGroupAmendmentCreate',
      "data.ref('group.id') in auth.ref('$user.memberships.group.roles.actionRights.group.id') && " +
        "'amendments' in auth.ref('$user.memberships.group.roles.actionRights.resource') && " +
        "'create' in auth.ref('$user.memberships.group.roles.actionRights.action')",
      'hasGroupAmendmentDelete',
      "data.ref('group.id') in auth.ref('$user.memberships.group.roles.actionRights.group.id') && " +
        "'amendments' in auth.ref('$user.memberships.group.roles.actionRights.resource') && " +
        "'delete' in auth.ref('$user.memberships.group.roles.actionRights.action')",
    ],
    allow: {
      view: 'isPublicOrAuthenticatedOrAuthorized',
      create: 'isAuthenticated && hasGroupAmendmentCreate',
      update: 'isAuthor || isCollaborator',
      delete: 'isAuthor || hasGroupAmendmentDelete',
    },
  },
  amendmentCollaborators: {
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isSelf',
      'auth.id == data.ref("user.id")',
      'isAmendmentAuthor',
      'auth.id == data.ref("amendment.user.id")',
      'isGroupMember',
      'data.ref("amendment.group.id") in auth.ref("$user.memberships.group.id")',
      'isPublished',
      '"published" in data.ref("amendment.status")',
      'isAmendmentVisible',
      'isGroupMember || isPublished',
    ],
    allow: {
      view: 'isAmendmentVisible',
      create: 'isAmendmentAuthor',
      update: 'false',
      delete: 'isAmendmentAuthor || isSelf',
    },
  },
  amendmentPaths: {
    allow: {
      view: 'isAmendmentVisible',
      create: 'isAmendmentAuthor',
      update: 'isAmendmentAuthor',
      delete: 'isAmendmentAuthor',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isAmendmentAuthor',
      'auth.id == data.ref("amendment.user.id")',
      'isGroupMember',
      'data.ref("amendment.group.id") in auth.ref("$user.memberships.group.id")',
      'isPublished',
      '"published" in data.ref("amendment.status")',
      'isAmendmentVisible',
      'isGroupMember || isPublished',
    ],
  },
  amendmentVoteEntries: {
    allow: {
      view: 'canViewVote',
      create: 'isVoter && voteIsOpen',
      update: 'isVoter && voteIsOpen',
      delete: 'isVoter && voteIsOpen',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isVoter',
      'auth.id == data.ref("voter.id")',
      'canViewVote',
      'data.ref("amendmentVote.agendaItem.event.group.id") in auth.ref("$user.memberships.group.id")',
      'voteIsOpen',
      '"open" in data.ref("amendmentVote.status")',
    ],
  },
  amendmentVotes: {
    allow: {
      view: 'isEventParticipant || isGroupMember',
      create: 'hasManageVotes',
      update: 'hasManageVotes',
      delete: 'hasManageVotes',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isEventParticipant',
      'auth.id in data.ref("agendaItem.event.participants.user.id")',
      'isGroupMember',
      'data.ref("agendaItem.event.group.id") in auth.ref("$user.memberships.group.id")',
      'hasManageVotes',
      "data.ref('agendaItem.event.group.id') in auth.ref('$user.memberships.group.roles.actionRights.group.id') && " +
        "'events' in auth.ref('$user.memberships.group.roles.actionRights.resource') && " +
        "'manage_votes' in auth.ref('$user.memberships.group.roles.actionRights.action')",
    ],
  },
  changeRequests: {
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isCreator',
      'auth.id == data.ref("creator.id")',
      'canViewAmendmentVote',
      'data.ref("amendmentVote.agendaItem.event.group.id") in auth.ref("$user.memberships.group.id")',
      'hasManageVotes',
      "data.ref('amendmentVote.agendaItem.event.group.id') in auth.ref('$user.memberships.group.roles.actionRights.group.id') && " +
        "'events' in auth.ref('$user.memberships.group.roles.actionRights.resource') && " +
        "'manage_votes' in auth.ref('$user.memberships.group.roles.actionRights.action')",
    ],
    allow: {
      view: 'canViewAmendmentVote',
      create: 'canViewAmendmentVote',
      update: 'isCreator',
      delete: 'isCreator || hasManageVotes',
    },
  },
  changeRequestVotes: {
    allow: {
      view: 'canViewChangeRequest',
      create: 'isVoter && canViewChangeRequest',
      update: 'isVoter',
      delete: 'isVoter',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isVoter',
      'auth.id == data.ref("voter.id")',
      'canViewChangeRequest',
      'data.ref("changeRequest.amendmentVote.agendaItem.event.group.id") in auth.ref("$user.memberships.group.id")',
    ],
  },
  threads: {
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isCreator',
      'auth.id == data.ref("creator.id")',
      'isGroupMember',
      'data.ref("amendment.group.id") in auth.ref("$user.memberships.group.id")',
      'isPublished',
      '"published" in data.ref("amendment.status")',
      'isAmendmentVisible',
      'isGroupMember || isPublished',
    ],
    allow: {
      view: 'isAmendmentVisible',
      create: 'isAmendmentVisible',
      update: 'isCreator',
      delete: 'isCreator',
    },
  },
  comments: {
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isCreator',
      'auth.id == data.ref("creator.id")',
      'isThreadAmendmentGroupMember',
      'data.ref("thread.amendment.group.id") in auth.ref("$user.memberships.group.id")',
      'isThreadAmendmentPublished',
      '"published" in data.ref("thread.amendment.status")',
      'isBlogGroupMember',
      'data.ref("blog.group.id") in auth.ref("$user.memberships.group.id")',
      'isBlogPublished',
      'true in data.ref("blog.published")',
      'isContentVisible',
      'isThreadAmendmentGroupMember || isThreadAmendmentPublished || isBlogGroupMember || isBlogPublished',
    ],
    allow: {
      view: 'isContentVisible',
      create: 'isContentVisible',
      update: 'isCreator',
      delete: 'isCreator',
    },
  },
  threadVotes: {
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isVoter',
      'auth.id == data.ref("user.id")',
      'isGroupMember',
      'data.ref("thread.amendment.group.id") in auth.ref("$user.memberships.group.id")',
      'isPublished',
      '"published" in data.ref("thread.amendment.status")',
      'isThreadVisible',
      'isGroupMember || isPublished',
    ],
    allow: {
      view: 'isThreadVisible',
      create: 'isVoter && isThreadVisible',
      update: 'isVoter',
      delete: 'isVoter',
    },
  },
  commentVotes: {
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isVoter',
      'auth.id == data.ref("user.id")',
      'isAmendmentGroupMember',
      'data.ref("comment.thread.amendment.group.id") in auth.ref("$user.memberships.group.id")',
      'isBlogPublished',
      'true in data.ref("comment.blog.published")',
      'isCommentVisible',
      'isAmendmentGroupMember || isBlogPublished',
    ],
    allow: {
      view: 'isCommentVisible',
      create: 'isVoter && isCommentVisible',
      update: 'isVoter',
      delete: 'isVoter',
    },
  },
  documentCollaborators: {
    allow: {
      view: 'isDocumentVisible',
      create: 'isDocumentOwner',
      update: 'isDocumentOwner',
      delete: 'isDocumentOwner || isSelf',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isSelf',
      'auth.id == data.ref("user.id")',
      'isDocumentOwner',
      'auth.id == data.ref("document.owner.id")',
      'isDocumentVisible',
      'auth.id == data.ref("document.owner.id") || auth.id in data.ref("document.collaborators.user.id")',
    ],
  },
  documentCursors: {
    allow: {
      view: 'isDocumentCollaborator',
      create: 'isDocumentCollaborator && isSelf',
      update: 'isSelf',
      delete: 'isSelf',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isSelf',
      'auth.id == data.ref("user.id")',
      'isDocumentCollaborator',
      'auth.id == data.ref("document.owner.id") || auth.id in data.ref("document.collaborators.user.id")',
    ],
  },
  documents: {
    allow: {
      view: 'isOwner || isCollaborator || isGroupMember',
      create: 'isAuthenticated',
      update: 'isOwner || isCollaborator',
      delete: 'isOwner',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isOwner',
      'auth.id == data.ref("owner.id")',
      'isCollaborator',
      'auth.id in data.ref("collaborators.user.id")',
      'isGroupMember',
      'data.ref("group.id") in auth.ref("$user.memberships.group.id")',
    ],
  },
  documentVersions: {
    allow: {
      view: 'isDocumentCollaborator',
      create: 'isDocumentCollaborator',
      update: 'false',
      delete: 'isDocumentOwner',
    },
    bind: [
      'isAuthenticated',
      'auth.id != null',
      'isDocumentOwner',
      'auth.id == data.ref("document.owner.id")',
      'isDocumentCollaborator',
      'auth.id == data.ref("document.owner.id") || auth.id in data.ref("document.collaborators.user.id")',
    ],
  },
} satisfies InstantRules;

export default rules;
