import type { User } from '../types/user.types';

export const USER: User = {
  name: 'Sarah Johnson',
  subtitle: 'Constitutional Law Expert',
  avatar: 'https://i.pravatar.cc/150?u=sarah',
  stats: [
    { label: 'Amendments', value: 143 },
    { label: 'Followers', value: 2.5, unit: 'k' },
    { label: 'Following', value: 328 },
    { label: 'Network', value: 78 },
    { label: 'Reputation', value: 4.8 },
  ],
  socialMedia: {
    whatsapp: 'https://wa.me/123456789',
    instagram: 'https://instagram.com/sarahjohnson',
    twitter: 'https://x.com/sarahjconst',
    facebook: 'https://facebook.com/sarahjohnson',
    snapchat: 'https://snapchat.com/add/sarahjlaw',
  },
  about:
    'Political scientist specializing in comparative constitutional design. Worked on constitutional reforms in 7 countries across Europe and Africa. Passionate about democratic innovations and citizen participation.',
  contact: {
    email: 'sarah.johnson@politics.org',
    twitter: '@sarahjconst',
    website: 'sarahjohnson.policy.org',
    location: 'Brussels, Belgium',
  },
  statements: [
    {
      id: 1,
      text: "Constitutional courts should be more representative of society's diversity.",
      tag: 'Judiciary',
    },
    {
      id: 2,
      text: 'Digital democracy tools can increase citizen participation in policymaking.',
      tag: 'Participation',
    },
    {
      id: 3,
      text: 'Federalism offers the best balance between unity and autonomy.',
      tag: 'Structure',
    },
    {
      id: 4,
      text: 'Term limits are essential for preventing power concentration.',
      tag: 'Governance',
    },
  ],
  blogs: [
    {
      id: 1,
      title: 'Reimagining Parliamentary Oversight',
      date: 'Mar 15, 2023',
      likes: 324,
      comments: 47,
    },
    {
      id: 2,
      title: "The Case for Citizens' Assemblies",
      date: 'Feb 2, 2023',
      likes: 521,
      comments: 83,
    },
    { id: 3, title: 'Digital Constitutionalism', date: 'Jan 10, 2023', likes: 187, comments: 32 },
  ],
  groups: [
    {
      id: 1,
      name: 'Constitutional Reform Network',
      members: 1243,
      role: 'Founder',
      description: 'Working to modernize constitutional frameworks across Europe',
      tags: ['constitution', 'reform', 'policy', 'governance'],
      amendments: 8,
      events: 12,
      abbr: 'CRN',
    },
    {
      id: 2,
      name: 'Democracy Innovations Lab',
      members: 567,
      role: 'Member',
      description: 'Researching new forms of democratic participation',
      tags: ['democracy', 'innovation', 'research', 'participation'],
      amendments: 3,
      events: 5,
      abbr: 'DIL',
    },
    {
      id: 3,
      name: 'Judicial Independence Initiative',
      members: 389,
      role: 'Advisor',
      description: 'Advocating for stronger protections for courts worldwide',
      tags: ['judiciary', 'independence', 'advocacy', 'courts'],
      amendments: 4,
      events: 2,
      abbr: 'JII',
    },
  ],
  amendments: [
    {
      id: 1,
      code: 'CON-27',
      title: 'Article 27 Reform Proposal',
      subtitle: 'Increasing judicial diversity through appointment reform',
      status: 'Under Review',
      supporters: 1243,
      date: 'Apr 5, 2023',
      tags: ['judicial', 'diversity', 'reform', 'appointments'],
    },
    {
      id: 2,
      code: 'ELC-14',
      title: 'Electoral System Amendment',
      subtitle: 'Moving from first-past-the-post to proportional representation',
      status: 'Passed',
      supporters: 2789,
      date: 'Dec 15, 2022',
      tags: ['electoral', 'voting', 'democracy', 'representation'],
    },
    {
      id: 3,
      code: 'JUD-08',
      title: 'Judicial Appointment Procedure',
      subtitle: 'New transparent process for selecting constitutional judges',
      status: 'Drafting',
      supporters: 342,
      date: 'May 3, 2023',
      tags: ['judiciary', 'transparency', 'selection', 'governance'],
    },
    {
      id: 4,
      code: 'TRM-52',
      title: 'Term Limits for Justices',
      subtitle: 'Proposal for 12-year term limits for Supreme Court justices',
      status: 'Rejected',
      supporters: 1876,
      date: 'Jan 22, 2023',
      tags: ['term-limits', 'judiciary', 'court-reform', 'accountability'],
    },
  ],
};
