/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsTestsRouteImport } from './routes/projects/tests'
import { Route as ProjectsTasksRouteImport } from './routes/projects/tasks'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as UserIdRoomRouteImport } from './routes/user/$id/room'
import { Route as UserIdNetworkRouteImport } from './routes/user/$id/network'
import { Route as UserIdSettingsTsxIndexRouteImport } from './routes/user/$id/settings.tsx/index'
import { Route as UserIdSettingsTsxSocialsRouteImport } from './routes/user/$id/settings.tsx/socials'
import { Route as UserIdSettingsTsxNotificationsRouteImport } from './routes/user/$id/settings.tsx/notifications'
import { Route as UserIdSettingsTsxGroupsRouteImport } from './routes/user/$id/settings.tsx/groups'
import { Route as UserIdSettingsTsxGeneralRouteImport } from './routes/user/$id/settings.tsx/general'
import { Route as UserIdSettingsTsxContactRouteImport } from './routes/user/$id/settings.tsx/contact'
import { Route as UserIdSettingsTsxAccountRouteImport } from './routes/user/$id/settings.tsx/account'
import { Route as UserIdSettingsTsxFollowshipIndexRouteImport } from './routes/user/$id/settings.tsx/followship/index'
import { Route as UserIdSettingsTsxFollowshipFollowingsRouteImport } from './routes/user/$id/settings.tsx/followship/followings'
import { Route as UserIdSettingsTsxFollowshipFollowersRouteImport } from './routes/user/$id/settings.tsx/followship/followers'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTestsRoute = ProjectsTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsTasksRoute = ProjectsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectsRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoomRoute = UserIdRoomRouteImport.update({
  id: '/user/$id/room',
  path: '/user/$id/room',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdNetworkRoute = UserIdNetworkRouteImport.update({
  id: '/user/$id/network',
  path: '/user/$id/network',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsTsxIndexRoute = UserIdSettingsTsxIndexRouteImport.update({
  id: '/user/$id/settings/tsx/',
  path: '/user/$id/settings/tsx/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsTsxSocialsRoute =
  UserIdSettingsTsxSocialsRouteImport.update({
    id: '/user/$id/settings/tsx/socials',
    path: '/user/$id/settings/tsx/socials',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsTsxNotificationsRoute =
  UserIdSettingsTsxNotificationsRouteImport.update({
    id: '/user/$id/settings/tsx/notifications',
    path: '/user/$id/settings/tsx/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsTsxGroupsRoute = UserIdSettingsTsxGroupsRouteImport.update({
  id: '/user/$id/settings/tsx/groups',
  path: '/user/$id/settings/tsx/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsTsxGeneralRoute =
  UserIdSettingsTsxGeneralRouteImport.update({
    id: '/user/$id/settings/tsx/general',
    path: '/user/$id/settings/tsx/general',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsTsxContactRoute =
  UserIdSettingsTsxContactRouteImport.update({
    id: '/user/$id/settings/tsx/contact',
    path: '/user/$id/settings/tsx/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsTsxAccountRoute =
  UserIdSettingsTsxAccountRouteImport.update({
    id: '/user/$id/settings/tsx/account',
    path: '/user/$id/settings/tsx/account',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsTsxFollowshipIndexRoute =
  UserIdSettingsTsxFollowshipIndexRouteImport.update({
    id: '/user/$id/settings/tsx/followship/',
    path: '/user/$id/settings/tsx/followship/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsTsxFollowshipFollowingsRoute =
  UserIdSettingsTsxFollowshipFollowingsRouteImport.update({
    id: '/user/$id/settings/tsx/followship/followings',
    path: '/user/$id/settings/tsx/followship/followings',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsTsxFollowshipFollowersRoute =
  UserIdSettingsTsxFollowshipFollowersRouteImport.update({
    id: '/user/$id/settings/tsx/followship/followers',
    path: '/user/$id/settings/tsx/followship/followers',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/flow': typeof FlowRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/tests': typeof ProjectsTestsRoute
  '/user/$id/network': typeof UserIdNetworkRoute
  '/user/$id/room': typeof UserIdRoomRoute
  '/user/$id': typeof UserIdIndexRoute
  '/user/$id/settings/tsx/account': typeof UserIdSettingsTsxAccountRoute
  '/user/$id/settings/tsx/contact': typeof UserIdSettingsTsxContactRoute
  '/user/$id/settings/tsx/general': typeof UserIdSettingsTsxGeneralRoute
  '/user/$id/settings/tsx/groups': typeof UserIdSettingsTsxGroupsRoute
  '/user/$id/settings/tsx/notifications': typeof UserIdSettingsTsxNotificationsRoute
  '/user/$id/settings/tsx/socials': typeof UserIdSettingsTsxSocialsRoute
  '/user/$id/settings/tsx': typeof UserIdSettingsTsxIndexRoute
  '/user/$id/settings/tsx/followship/followers': typeof UserIdSettingsTsxFollowshipFollowersRoute
  '/user/$id/settings/tsx/followship/followings': typeof UserIdSettingsTsxFollowshipFollowingsRoute
  '/user/$id/settings/tsx/followship': typeof UserIdSettingsTsxFollowshipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/flow': typeof FlowRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/tests': typeof ProjectsTestsRoute
  '/user/$id/network': typeof UserIdNetworkRoute
  '/user/$id/room': typeof UserIdRoomRoute
  '/user/$id': typeof UserIdIndexRoute
  '/user/$id/settings/tsx/account': typeof UserIdSettingsTsxAccountRoute
  '/user/$id/settings/tsx/contact': typeof UserIdSettingsTsxContactRoute
  '/user/$id/settings/tsx/general': typeof UserIdSettingsTsxGeneralRoute
  '/user/$id/settings/tsx/groups': typeof UserIdSettingsTsxGroupsRoute
  '/user/$id/settings/tsx/notifications': typeof UserIdSettingsTsxNotificationsRoute
  '/user/$id/settings/tsx/socials': typeof UserIdSettingsTsxSocialsRoute
  '/user/$id/settings/tsx': typeof UserIdSettingsTsxIndexRoute
  '/user/$id/settings/tsx/followship/followers': typeof UserIdSettingsTsxFollowshipFollowersRoute
  '/user/$id/settings/tsx/followship/followings': typeof UserIdSettingsTsxFollowshipFollowingsRoute
  '/user/$id/settings/tsx/followship': typeof UserIdSettingsTsxFollowshipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/flow': typeof FlowRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/tests': typeof ProjectsTestsRoute
  '/user/$id/network': typeof UserIdNetworkRoute
  '/user/$id/room': typeof UserIdRoomRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/user/$id/settings/tsx/account': typeof UserIdSettingsTsxAccountRoute
  '/user/$id/settings/tsx/contact': typeof UserIdSettingsTsxContactRoute
  '/user/$id/settings/tsx/general': typeof UserIdSettingsTsxGeneralRoute
  '/user/$id/settings/tsx/groups': typeof UserIdSettingsTsxGroupsRoute
  '/user/$id/settings/tsx/notifications': typeof UserIdSettingsTsxNotificationsRoute
  '/user/$id/settings/tsx/socials': typeof UserIdSettingsTsxSocialsRoute
  '/user/$id/settings/tsx/': typeof UserIdSettingsTsxIndexRoute
  '/user/$id/settings/tsx/followship/followers': typeof UserIdSettingsTsxFollowshipFollowersRoute
  '/user/$id/settings/tsx/followship/followings': typeof UserIdSettingsTsxFollowshipFollowingsRoute
  '/user/$id/settings/tsx/followship/': typeof UserIdSettingsTsxFollowshipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flow'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/reports'
    | '/projects/tasks'
    | '/projects/tests'
    | '/user/$id/network'
    | '/user/$id/room'
    | '/user/$id'
    | '/user/$id/settings/tsx/account'
    | '/user/$id/settings/tsx/contact'
    | '/user/$id/settings/tsx/general'
    | '/user/$id/settings/tsx/groups'
    | '/user/$id/settings/tsx/notifications'
    | '/user/$id/settings/tsx/socials'
    | '/user/$id/settings/tsx'
    | '/user/$id/settings/tsx/followship/followers'
    | '/user/$id/settings/tsx/followship/followings'
    | '/user/$id/settings/tsx/followship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flow'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/reports'
    | '/projects/tasks'
    | '/projects/tests'
    | '/user/$id/network'
    | '/user/$id/room'
    | '/user/$id'
    | '/user/$id/settings/tsx/account'
    | '/user/$id/settings/tsx/contact'
    | '/user/$id/settings/tsx/general'
    | '/user/$id/settings/tsx/groups'
    | '/user/$id/settings/tsx/notifications'
    | '/user/$id/settings/tsx/socials'
    | '/user/$id/settings/tsx'
    | '/user/$id/settings/tsx/followship/followers'
    | '/user/$id/settings/tsx/followship/followings'
    | '/user/$id/settings/tsx/followship'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flow'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/reports'
    | '/projects/tasks'
    | '/projects/tests'
    | '/user/$id/network'
    | '/user/$id/room'
    | '/user/$id/'
    | '/user/$id/settings/tsx/account'
    | '/user/$id/settings/tsx/contact'
    | '/user/$id/settings/tsx/general'
    | '/user/$id/settings/tsx/groups'
    | '/user/$id/settings/tsx/notifications'
    | '/user/$id/settings/tsx/socials'
    | '/user/$id/settings/tsx/'
    | '/user/$id/settings/tsx/followship/followers'
    | '/user/$id/settings/tsx/followship/followings'
    | '/user/$id/settings/tsx/followship/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FilesRoute: typeof FilesRoute
  FlowRoute: typeof FlowRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UserIdNetworkRoute: typeof UserIdNetworkRoute
  UserIdRoomRoute: typeof UserIdRoomRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  UserIdSettingsTsxAccountRoute: typeof UserIdSettingsTsxAccountRoute
  UserIdSettingsTsxContactRoute: typeof UserIdSettingsTsxContactRoute
  UserIdSettingsTsxGeneralRoute: typeof UserIdSettingsTsxGeneralRoute
  UserIdSettingsTsxGroupsRoute: typeof UserIdSettingsTsxGroupsRoute
  UserIdSettingsTsxNotificationsRoute: typeof UserIdSettingsTsxNotificationsRoute
  UserIdSettingsTsxSocialsRoute: typeof UserIdSettingsTsxSocialsRoute
  UserIdSettingsTsxIndexRoute: typeof UserIdSettingsTsxIndexRoute
  UserIdSettingsTsxFollowshipFollowersRoute: typeof UserIdSettingsTsxFollowshipFollowersRoute
  UserIdSettingsTsxFollowshipFollowingsRoute: typeof UserIdSettingsTsxFollowshipFollowingsRoute
  UserIdSettingsTsxFollowshipIndexRoute: typeof UserIdSettingsTsxFollowshipIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/tests': {
      id: '/projects/tests'
      path: '/tests'
      fullPath: '/projects/tests'
      preLoaderRoute: typeof ProjectsTestsRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/tasks': {
      id: '/projects/tasks'
      path: '/tasks'
      fullPath: '/projects/tasks'
      preLoaderRoute: typeof ProjectsTasksRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/room': {
      id: '/user/$id/room'
      path: '/user/$id/room'
      fullPath: '/user/$id/room'
      preLoaderRoute: typeof UserIdRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/network': {
      id: '/user/$id/network'
      path: '/user/$id/network'
      fullPath: '/user/$id/network'
      preLoaderRoute: typeof UserIdNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/': {
      id: '/user/$id/settings/tsx/'
      path: '/user/$id/settings/tsx'
      fullPath: '/user/$id/settings/tsx'
      preLoaderRoute: typeof UserIdSettingsTsxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/socials': {
      id: '/user/$id/settings/tsx/socials'
      path: '/user/$id/settings/tsx/socials'
      fullPath: '/user/$id/settings/tsx/socials'
      preLoaderRoute: typeof UserIdSettingsTsxSocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/notifications': {
      id: '/user/$id/settings/tsx/notifications'
      path: '/user/$id/settings/tsx/notifications'
      fullPath: '/user/$id/settings/tsx/notifications'
      preLoaderRoute: typeof UserIdSettingsTsxNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/groups': {
      id: '/user/$id/settings/tsx/groups'
      path: '/user/$id/settings/tsx/groups'
      fullPath: '/user/$id/settings/tsx/groups'
      preLoaderRoute: typeof UserIdSettingsTsxGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/general': {
      id: '/user/$id/settings/tsx/general'
      path: '/user/$id/settings/tsx/general'
      fullPath: '/user/$id/settings/tsx/general'
      preLoaderRoute: typeof UserIdSettingsTsxGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/contact': {
      id: '/user/$id/settings/tsx/contact'
      path: '/user/$id/settings/tsx/contact'
      fullPath: '/user/$id/settings/tsx/contact'
      preLoaderRoute: typeof UserIdSettingsTsxContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/account': {
      id: '/user/$id/settings/tsx/account'
      path: '/user/$id/settings/tsx/account'
      fullPath: '/user/$id/settings/tsx/account'
      preLoaderRoute: typeof UserIdSettingsTsxAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/followship/': {
      id: '/user/$id/settings/tsx/followship/'
      path: '/user/$id/settings/tsx/followship'
      fullPath: '/user/$id/settings/tsx/followship'
      preLoaderRoute: typeof UserIdSettingsTsxFollowshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/followship/followings': {
      id: '/user/$id/settings/tsx/followship/followings'
      path: '/user/$id/settings/tsx/followship/followings'
      fullPath: '/user/$id/settings/tsx/followship/followings'
      preLoaderRoute: typeof UserIdSettingsTsxFollowshipFollowingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/tsx/followship/followers': {
      id: '/user/$id/settings/tsx/followship/followers'
      path: '/user/$id/settings/tsx/followship/followers'
      fullPath: '/user/$id/settings/tsx/followship/followers'
      preLoaderRoute: typeof UserIdSettingsTsxFollowshipFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsTasksRoute: typeof ProjectsTasksRoute
  ProjectsTestsRoute: typeof ProjectsTestsRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsTasksRoute: ProjectsTasksRoute,
  ProjectsTestsRoute: ProjectsTestsRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FilesRoute: FilesRoute,
  FlowRoute: FlowRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UserIdNetworkRoute: UserIdNetworkRoute,
  UserIdRoomRoute: UserIdRoomRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  UserIdSettingsTsxAccountRoute: UserIdSettingsTsxAccountRoute,
  UserIdSettingsTsxContactRoute: UserIdSettingsTsxContactRoute,
  UserIdSettingsTsxGeneralRoute: UserIdSettingsTsxGeneralRoute,
  UserIdSettingsTsxGroupsRoute: UserIdSettingsTsxGroupsRoute,
  UserIdSettingsTsxNotificationsRoute: UserIdSettingsTsxNotificationsRoute,
  UserIdSettingsTsxSocialsRoute: UserIdSettingsTsxSocialsRoute,
  UserIdSettingsTsxIndexRoute: UserIdSettingsTsxIndexRoute,
  UserIdSettingsTsxFollowshipFollowersRoute:
    UserIdSettingsTsxFollowshipFollowersRoute,
  UserIdSettingsTsxFollowshipFollowingsRoute:
    UserIdSettingsTsxFollowshipFollowingsRoute,
  UserIdSettingsTsxFollowshipIndexRoute: UserIdSettingsTsxFollowshipIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
