/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsTestsRouteImport } from './routes/projects/tests'
import { Route as ProjectsTasksRouteImport } from './routes/projects/tasks'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as UserIdRoomRouteImport } from './routes/user/$id/room'
import { Route as UserIdNetworkRouteImport } from './routes/user/$id/network'
import { Route as UserIdSettingsIndexRouteImport } from './routes/user/$id/settings/index'
import { Route as UserIdSettingsSocialsRouteImport } from './routes/user/$id/settings/socials'
import { Route as UserIdSettingsNotificationsRouteImport } from './routes/user/$id/settings/notifications'
import { Route as UserIdSettingsGroupsRouteImport } from './routes/user/$id/settings/groups'
import { Route as UserIdSettingsGeneralRouteImport } from './routes/user/$id/settings/general'
import { Route as UserIdSettingsContactRouteImport } from './routes/user/$id/settings/contact'
import { Route as UserIdSettingsAccountRouteImport } from './routes/user/$id/settings/account'
import { Route as UserIdSettingsFollowshipIndexRouteImport } from './routes/user/$id/settings/followship/index'
import { Route as UserIdSettingsFollowshipFollowingsRouteImport } from './routes/user/$id/settings/followship/followings'
import { Route as UserIdSettingsFollowshipFollowersRouteImport } from './routes/user/$id/settings/followship/followers'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTestsRoute = ProjectsTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsTasksRoute = ProjectsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectsRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoomRoute = UserIdRoomRouteImport.update({
  id: '/user/$id/room',
  path: '/user/$id/room',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdNetworkRoute = UserIdNetworkRouteImport.update({
  id: '/user/$id/network',
  path: '/user/$id/network',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsIndexRoute = UserIdSettingsIndexRouteImport.update({
  id: '/user/$id/settings/',
  path: '/user/$id/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsSocialsRoute = UserIdSettingsSocialsRouteImport.update({
  id: '/user/$id/settings/socials',
  path: '/user/$id/settings/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsNotificationsRoute =
  UserIdSettingsNotificationsRouteImport.update({
    id: '/user/$id/settings/notifications',
    path: '/user/$id/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsGroupsRoute = UserIdSettingsGroupsRouteImport.update({
  id: '/user/$id/settings/groups',
  path: '/user/$id/settings/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsGeneralRoute = UserIdSettingsGeneralRouteImport.update({
  id: '/user/$id/settings/general',
  path: '/user/$id/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsContactRoute = UserIdSettingsContactRouteImport.update({
  id: '/user/$id/settings/contact',
  path: '/user/$id/settings/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsAccountRoute = UserIdSettingsAccountRouteImport.update({
  id: '/user/$id/settings/account',
  path: '/user/$id/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsFollowshipIndexRoute =
  UserIdSettingsFollowshipIndexRouteImport.update({
    id: '/user/$id/settings/followship/',
    path: '/user/$id/settings/followship/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsFollowshipFollowingsRoute =
  UserIdSettingsFollowshipFollowingsRouteImport.update({
    id: '/user/$id/settings/followship/followings',
    path: '/user/$id/settings/followship/followings',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIdSettingsFollowshipFollowersRoute =
  UserIdSettingsFollowshipFollowersRouteImport.update({
    id: '/user/$id/settings/followship/followers',
    path: '/user/$id/settings/followship/followers',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/flow': typeof FlowRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/tests': typeof ProjectsTestsRoute
  '/user/$id/network': typeof UserIdNetworkRoute
  '/user/$id/room': typeof UserIdRoomRoute
  '/user/$id': typeof UserIdIndexRoute
  '/user/$id/settings/account': typeof UserIdSettingsAccountRoute
  '/user/$id/settings/contact': typeof UserIdSettingsContactRoute
  '/user/$id/settings/general': typeof UserIdSettingsGeneralRoute
  '/user/$id/settings/groups': typeof UserIdSettingsGroupsRoute
  '/user/$id/settings/notifications': typeof UserIdSettingsNotificationsRoute
  '/user/$id/settings/socials': typeof UserIdSettingsSocialsRoute
  '/user/$id/settings': typeof UserIdSettingsIndexRoute
  '/user/$id/settings/followship/followers': typeof UserIdSettingsFollowshipFollowersRoute
  '/user/$id/settings/followship/followings': typeof UserIdSettingsFollowshipFollowingsRoute
  '/user/$id/settings/followship': typeof UserIdSettingsFollowshipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/flow': typeof FlowRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/tests': typeof ProjectsTestsRoute
  '/user/$id/network': typeof UserIdNetworkRoute
  '/user/$id/room': typeof UserIdRoomRoute
  '/user/$id': typeof UserIdIndexRoute
  '/user/$id/settings/account': typeof UserIdSettingsAccountRoute
  '/user/$id/settings/contact': typeof UserIdSettingsContactRoute
  '/user/$id/settings/general': typeof UserIdSettingsGeneralRoute
  '/user/$id/settings/groups': typeof UserIdSettingsGroupsRoute
  '/user/$id/settings/notifications': typeof UserIdSettingsNotificationsRoute
  '/user/$id/settings/socials': typeof UserIdSettingsSocialsRoute
  '/user/$id/settings': typeof UserIdSettingsIndexRoute
  '/user/$id/settings/followship/followers': typeof UserIdSettingsFollowshipFollowersRoute
  '/user/$id/settings/followship/followings': typeof UserIdSettingsFollowshipFollowingsRoute
  '/user/$id/settings/followship': typeof UserIdSettingsFollowshipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/flow': typeof FlowRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/projects/tasks': typeof ProjectsTasksRoute
  '/projects/tests': typeof ProjectsTestsRoute
  '/user/$id/network': typeof UserIdNetworkRoute
  '/user/$id/room': typeof UserIdRoomRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/user/$id/settings/account': typeof UserIdSettingsAccountRoute
  '/user/$id/settings/contact': typeof UserIdSettingsContactRoute
  '/user/$id/settings/general': typeof UserIdSettingsGeneralRoute
  '/user/$id/settings/groups': typeof UserIdSettingsGroupsRoute
  '/user/$id/settings/notifications': typeof UserIdSettingsNotificationsRoute
  '/user/$id/settings/socials': typeof UserIdSettingsSocialsRoute
  '/user/$id/settings/': typeof UserIdSettingsIndexRoute
  '/user/$id/settings/followship/followers': typeof UserIdSettingsFollowshipFollowersRoute
  '/user/$id/settings/followship/followings': typeof UserIdSettingsFollowshipFollowingsRoute
  '/user/$id/settings/followship/': typeof UserIdSettingsFollowshipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flow'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/reports'
    | '/projects/tasks'
    | '/projects/tests'
    | '/user/$id/network'
    | '/user/$id/room'
    | '/user/$id'
    | '/user/$id/settings/account'
    | '/user/$id/settings/contact'
    | '/user/$id/settings/general'
    | '/user/$id/settings/groups'
    | '/user/$id/settings/notifications'
    | '/user/$id/settings/socials'
    | '/user/$id/settings'
    | '/user/$id/settings/followship/followers'
    | '/user/$id/settings/followship/followings'
    | '/user/$id/settings/followship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flow'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/reports'
    | '/projects/tasks'
    | '/projects/tests'
    | '/user/$id/network'
    | '/user/$id/room'
    | '/user/$id'
    | '/user/$id/settings/account'
    | '/user/$id/settings/contact'
    | '/user/$id/settings/general'
    | '/user/$id/settings/groups'
    | '/user/$id/settings/notifications'
    | '/user/$id/settings/socials'
    | '/user/$id/settings'
    | '/user/$id/settings/followship/followers'
    | '/user/$id/settings/followship/followings'
    | '/user/$id/settings/followship'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flow'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/dashboard/analytics'
    | '/dashboard/reports'
    | '/projects/tasks'
    | '/projects/tests'
    | '/user/$id/network'
    | '/user/$id/room'
    | '/user/$id/'
    | '/user/$id/settings/account'
    | '/user/$id/settings/contact'
    | '/user/$id/settings/general'
    | '/user/$id/settings/groups'
    | '/user/$id/settings/notifications'
    | '/user/$id/settings/socials'
    | '/user/$id/settings/'
    | '/user/$id/settings/followship/followers'
    | '/user/$id/settings/followship/followings'
    | '/user/$id/settings/followship/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FilesRoute: typeof FilesRoute
  FlowRoute: typeof FlowRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UserIdNetworkRoute: typeof UserIdNetworkRoute
  UserIdRoomRoute: typeof UserIdRoomRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  UserIdSettingsAccountRoute: typeof UserIdSettingsAccountRoute
  UserIdSettingsContactRoute: typeof UserIdSettingsContactRoute
  UserIdSettingsGeneralRoute: typeof UserIdSettingsGeneralRoute
  UserIdSettingsGroupsRoute: typeof UserIdSettingsGroupsRoute
  UserIdSettingsNotificationsRoute: typeof UserIdSettingsNotificationsRoute
  UserIdSettingsSocialsRoute: typeof UserIdSettingsSocialsRoute
  UserIdSettingsIndexRoute: typeof UserIdSettingsIndexRoute
  UserIdSettingsFollowshipFollowersRoute: typeof UserIdSettingsFollowshipFollowersRoute
  UserIdSettingsFollowshipFollowingsRoute: typeof UserIdSettingsFollowshipFollowingsRoute
  UserIdSettingsFollowshipIndexRoute: typeof UserIdSettingsFollowshipIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/tests': {
      id: '/projects/tests'
      path: '/tests'
      fullPath: '/projects/tests'
      preLoaderRoute: typeof ProjectsTestsRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/tasks': {
      id: '/projects/tasks'
      path: '/tasks'
      fullPath: '/projects/tasks'
      preLoaderRoute: typeof ProjectsTasksRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/room': {
      id: '/user/$id/room'
      path: '/user/$id/room'
      fullPath: '/user/$id/room'
      preLoaderRoute: typeof UserIdRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/network': {
      id: '/user/$id/network'
      path: '/user/$id/network'
      fullPath: '/user/$id/network'
      preLoaderRoute: typeof UserIdNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/': {
      id: '/user/$id/settings/'
      path: '/user/$id/settings'
      fullPath: '/user/$id/settings'
      preLoaderRoute: typeof UserIdSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/socials': {
      id: '/user/$id/settings/socials'
      path: '/user/$id/settings/socials'
      fullPath: '/user/$id/settings/socials'
      preLoaderRoute: typeof UserIdSettingsSocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/notifications': {
      id: '/user/$id/settings/notifications'
      path: '/user/$id/settings/notifications'
      fullPath: '/user/$id/settings/notifications'
      preLoaderRoute: typeof UserIdSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/groups': {
      id: '/user/$id/settings/groups'
      path: '/user/$id/settings/groups'
      fullPath: '/user/$id/settings/groups'
      preLoaderRoute: typeof UserIdSettingsGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/general': {
      id: '/user/$id/settings/general'
      path: '/user/$id/settings/general'
      fullPath: '/user/$id/settings/general'
      preLoaderRoute: typeof UserIdSettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/contact': {
      id: '/user/$id/settings/contact'
      path: '/user/$id/settings/contact'
      fullPath: '/user/$id/settings/contact'
      preLoaderRoute: typeof UserIdSettingsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/account': {
      id: '/user/$id/settings/account'
      path: '/user/$id/settings/account'
      fullPath: '/user/$id/settings/account'
      preLoaderRoute: typeof UserIdSettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/followship/': {
      id: '/user/$id/settings/followship/'
      path: '/user/$id/settings/followship'
      fullPath: '/user/$id/settings/followship'
      preLoaderRoute: typeof UserIdSettingsFollowshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/followship/followings': {
      id: '/user/$id/settings/followship/followings'
      path: '/user/$id/settings/followship/followings'
      fullPath: '/user/$id/settings/followship/followings'
      preLoaderRoute: typeof UserIdSettingsFollowshipFollowingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/settings/followship/followers': {
      id: '/user/$id/settings/followship/followers'
      path: '/user/$id/settings/followship/followers'
      fullPath: '/user/$id/settings/followship/followers'
      preLoaderRoute: typeof UserIdSettingsFollowshipFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsTasksRoute: typeof ProjectsTasksRoute
  ProjectsTestsRoute: typeof ProjectsTestsRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsTasksRoute: ProjectsTasksRoute,
  ProjectsTestsRoute: ProjectsTestsRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FilesRoute: FilesRoute,
  FlowRoute: FlowRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UserIdNetworkRoute: UserIdNetworkRoute,
  UserIdRoomRoute: UserIdRoomRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  UserIdSettingsAccountRoute: UserIdSettingsAccountRoute,
  UserIdSettingsContactRoute: UserIdSettingsContactRoute,
  UserIdSettingsGeneralRoute: UserIdSettingsGeneralRoute,
  UserIdSettingsGroupsRoute: UserIdSettingsGroupsRoute,
  UserIdSettingsNotificationsRoute: UserIdSettingsNotificationsRoute,
  UserIdSettingsSocialsRoute: UserIdSettingsSocialsRoute,
  UserIdSettingsIndexRoute: UserIdSettingsIndexRoute,
  UserIdSettingsFollowshipFollowersRoute:
    UserIdSettingsFollowshipFollowersRoute,
  UserIdSettingsFollowshipFollowingsRoute:
    UserIdSettingsFollowshipFollowingsRoute,
  UserIdSettingsFollowshipIndexRoute: UserIdSettingsFollowshipIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
